---
slack_workspace_name: My Slack Workspace

deployment_regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - ap-south-1
  - ap-northeast-3
  - ap-northeast-2
  - ap-southeast-1
  - ap-southeast-2
  - ap-northeast-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - eu-north-1
  - sa-east-1

alternate_contacts:
  enabled: false

  default:
    billing:
      name: Finance Team
      title: Finance Team
      email: finance@example.com
      phone: "1234567890"
    operations:
      name: Operations Team
      title: Operations Team
      email: ops@example.com
      phone: "1234567890"
    security:
      name: Security Team
      title: Security Team
      email: security@example.com
      phone: "1234567890"

  "123456789012":
    billing:
      name: Another Finance Team
      title: Another Finance Team
      email: finance2@example.com
      phone: "2345678901"
    operations:
      name: Another Operation Team
      title: Another Operations Team
      email: ops2@example.com
      phone: "2345678901"
    security:
      name: Another Security Team
      title: Another Security Team
      email: security2@example.com
      phone: "2345678901"
